# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00df2639c3e007139b1ef087cc67f6e0"
name = "custom-app-rewardz"
handle = "custom-app-rewardz"
application_url = "https://acm-fought-patch-thunder.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = ["https://acm-fought-patch-thunder.trycloudflare.com/auth/callback", "https://acm-fought-patch-thunder.trycloudflare.com/auth/shopify/callback", "https://acm-fought-patch-thunder.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
